name: job with flow
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello! This is BUILD"
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello! This is TEST"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run : echo " Hello! This is deploy"
